// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ebhApi.Data;

#nullable disable

namespace ebhApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240618011253_MyMigration")]
    partial class MyMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EbhBasvurularSube", b =>
                {
                    b.Property<int>("EbhBasvuruYapilanSubeId")
                        .HasColumnType("int");

                    b.Property<int>("SubeyeYapilanBasvurularId")
                        .HasColumnType("int");

                    b.HasKey("EbhBasvuruYapilanSubeId", "SubeyeYapilanBasvurularId");

                    b.HasIndex("SubeyeYapilanBasvurularId");

                    b.ToTable("EbhBasvurularSube");
                });

            modelBuilder.Entity("EkipSube", b =>
                {
                    b.Property<int>("EkipSubesiId")
                        .HasColumnType("int");

                    b.Property<int>("SubeyeAitEkiplerId")
                        .HasColumnType("int");

                    b.HasKey("EkipSubesiId", "SubeyeAitEkiplerId");

                    b.HasIndex("SubeyeAitEkiplerId");

                    b.ToTable("EkipSube");
                });

            modelBuilder.Entity("ebhApi.Models.EbhBasvurular", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AcilMi")
                        .HasColumnType("bit");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdresTarif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BakimDurumu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CepNo1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CepNo2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Cinsiyet")
                        .HasColumnType("bit");

                    b.Property<bool?>("Depremzede")
                        .HasColumnType("bit");

                    b.Property<string>("EgitimDurum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EkipAciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EkipId")
                        .HasColumnType("int");

                    b.Property<string>("Heskod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HizmetAlacakKisi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IhbarDetay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IhbarSahibi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OdaSayi")
                        .HasColumnType("int");

                    b.Property<bool?>("Soybis")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TalepTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<long>("Tckn")
                        .HasColumnType("bigint");

                    b.Property<int>("Yas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EkipId");

                    b.ToTable("EbhBasvurulari");
                });

            modelBuilder.Entity("ebhApi.Models.Ekip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gorev")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ekipler");
                });

            modelBuilder.Entity("ebhApi.Models.Hastalik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EbhBasvurularId")
                        .HasColumnType("int");

                    b.Property<string>("HastalikAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EbhBasvurularId");

                    b.ToTable("Hastaliklar");
                });

            modelBuilder.Entity("ebhApi.Models.Sube", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SubeAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubeAdresi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubeTelefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subeler");
                });

            modelBuilder.Entity("ebhApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KullanicininEkipleriId")
                        .HasColumnType("int");

                    b.Property<int?>("KullanicininSubesiId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KullanicininEkipleriId");

                    b.HasIndex("KullanicininSubesiId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EbhBasvurularSube", b =>
                {
                    b.HasOne("ebhApi.Models.Sube", null)
                        .WithMany()
                        .HasForeignKey("EbhBasvuruYapilanSubeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ebhApi.Models.EbhBasvurular", null)
                        .WithMany()
                        .HasForeignKey("SubeyeYapilanBasvurularId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EkipSube", b =>
                {
                    b.HasOne("ebhApi.Models.Sube", null)
                        .WithMany()
                        .HasForeignKey("EkipSubesiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ebhApi.Models.Ekip", null)
                        .WithMany()
                        .HasForeignKey("SubeyeAitEkiplerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ebhApi.Models.EbhBasvurular", b =>
                {
                    b.HasOne("ebhApi.Models.Ekip", null)
                        .WithMany("EkibeAitBasvurular")
                        .HasForeignKey("EkipId");
                });

            modelBuilder.Entity("ebhApi.Models.Hastalik", b =>
                {
                    b.HasOne("ebhApi.Models.EbhBasvurular", null)
                        .WithMany("Hastaliklar")
                        .HasForeignKey("EbhBasvurularId");
                });

            modelBuilder.Entity("ebhApi.Models.User", b =>
                {
                    b.HasOne("ebhApi.Models.Ekip", "KullanicininEkipleri")
                        .WithMany("EkipUyeleri")
                        .HasForeignKey("KullanicininEkipleriId");

                    b.HasOne("ebhApi.Models.Sube", "KullanicininSubesi")
                        .WithMany("SubeyeAitKullanicilar")
                        .HasForeignKey("KullanicininSubesiId");

                    b.Navigation("KullanicininEkipleri");

                    b.Navigation("KullanicininSubesi");
                });

            modelBuilder.Entity("ebhApi.Models.EbhBasvurular", b =>
                {
                    b.Navigation("Hastaliklar");
                });

            modelBuilder.Entity("ebhApi.Models.Ekip", b =>
                {
                    b.Navigation("EkibeAitBasvurular");

                    b.Navigation("EkipUyeleri");
                });

            modelBuilder.Entity("ebhApi.Models.Sube", b =>
                {
                    b.Navigation("SubeyeAitKullanicilar");
                });
#pragma warning restore 612, 618
        }
    }
}
